# Generated by Django 6.1.1 on 2026-10-07 06:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('center', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_m', models.PositiveIntegerField(help_text='Search radius in metres.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=8)),
                ('osm_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list)),
                ('brand', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(help_text='When the pipeline last changed this place.')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when the place disappears from OpenStreetMap.', null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.area')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['area', 'closed_at'], name='places_plac_area_id_a5b4f2_idx')],
                'constraints': [models.UniqueConstraint(fields=('osm_type', 'osm_id'), name='unique_osm_element')],
            },
        ),
    ]
