# Generated by Django 5.2 on 2025-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberjayashop',
            name='image',
            field=models.ImageField(default=1, upload_to='shopimages/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cyberjayashop',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
