# Generated by Django 5.2 on 2025-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0002_cyberjayashop_image_alter_cyberjayashop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberjayashop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shopimages/'),
        ),
    ]
