# Generated by Django 5.2 on 2025-11-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0003_alter_cyberjayashop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberjayashop',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cyberjayashop',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cyberjayashop',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
