# Generated by Django 5.2 on 2025-11-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0004_cyberjayashop_latitude_cyberjayashop_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kualaLumpurShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shopimages/')),
            ],
        ),
    ]
