# Generated by Django 5.2 on 2025-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0007_shoplists'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplists',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
