# Generated by Django 5.2 on 2025-11-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0008_shoplists_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cyberjayaShop',
        ),
        migrations.DeleteModel(
            name='kualaLumpurShop',
        ),
        migrations.DeleteModel(
            name='kuchaiLamaShop',
        ),
    ]
