# Generated by Django 5.2 on 2025-11-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0009_delete_cyberjayashop_delete_kualalumpurshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplists',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
