# Generated by Django 5.2 on 2025-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodhunting', '0010_alter_shoplists_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplists',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
